2025-08-22 18:29:55,074 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:29:56,855 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:48:22,256 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:48:48,773 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-22 18:52:29,038 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 18:42:24,227 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 18:42:37,157 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 18:42:47,017 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:134]
2025-08-23 21:57:44,493 ERROR: Exception on /login [GET] [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py", line 83, in login
    return render_template('login.html')
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\templates\login.html", line 630, in top-level template code
    <form method="POST" action="{{ url_for('auth.resend_activation') }}">
    ^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.resend_activation'. Did you mean 'auth.activate' instead?
2025-08-23 21:57:56,087 ERROR: Exception on /login [GET] [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py", line 83, in login
    return render_template('login.html')
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\templates\login.html", line 630, in top-level template code
    <form method="POST" action="{{ url_for('auth.resend_activation') }}">
    ^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\prueba\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auth.resend_activation'. Did you mean 'auth.activate' instead?
2025-08-23 21:58:55,468 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:140]
2025-08-23 21:59:15,640 ERROR: Error preparando datos del usuario para localStorage: 'str' object has no attribute 'isoformat' [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py:55]
2025-08-23 23:22:04,397 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:140]
2025-08-23 23:38:30,879 INFO: Accediendo a la página de laboratorios [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\laboratorio_controller.py:18]
2025-08-23 23:38:30,899 INFO: Query base creada: SELECT laboratorio.id_laboratorio AS laboratorio_id_laboratorio, laboratorio.nombre_laboratorio AS laboratorio_nombre_laboratorio, laboratorio.disponibilidad AS laboratorio_disponibilidad, laboratorio.descripcion AS laboratorio_descripcion, laboratorio.imagen_url AS laboratorio_imagen_url, laboratorio.capacidad AS laboratorio_capacidad, laboratorio.horario AS laboratorio_horario, laboratorio.ubicacion AS laboratorio_ubicacion, laboratorio.telefono AS laboratorio_telefono, laboratorio.email_contacto AS laboratorio_email_contacto, laboratorio.superficie_m2 AS laboratorio_superficie_m2, laboratorio.equipamiento AS laboratorio_equipamiento, laboratorio.normas_uso AS laboratorio_normas_uso, laboratorio.requiere_capacitacion AS laboratorio_requiere_capacitacion, laboratorio.id_institucion AS laboratorio_id_institucion, laboratorio.id_area AS laboratorio_id_area, laboratorio.id_tipo_laboratorio AS laboratorio_id_tipo_laboratorio, laboratorio.id_encargado AS laboratorio_id_encargado, laboratorio.fecha_creacion AS laboratorio_fecha_creacion, laboratorio.fecha_modificacion AS laboratorio_fecha_modificacion 
FROM laboratorio [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\laboratorio_controller.py:32]
2025-08-23 23:38:30,951 INFO: Áreas encontradas: 21 [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\laboratorio_controller.py:55]
2025-08-23 23:38:30,953 INFO: Instituciones encontradas: 7 [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\laboratorio_controller.py:56]
2025-08-23 23:38:31,036 INFO: Laboratorios encontrados: 18 [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\laboratorio_controller.py:60]
2025-08-24 00:32:48,000 ERROR: Error preparando datos del usuario para localStorage: 'str' object has no attribute 'isoformat' [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\login_controller.py:55]
2025-08-24 01:03:15,947 INFO: Inicio de la aplicación [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\__init__.py:142]
2025-08-24 01:10:34,356 INFO: Accediendo a la página de laboratorios [in C:\Users\Cynthia Karina\Documents\Maestría\Tesis\Proyecto\app\controllers\laboratorio_controller.py:18]
